# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_marca_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.marca'),
        ),
    ]
