# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_modelo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombreMarca',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='nombreModelo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='tipouber',
            field=models.CharField(choices=[('UX', 'Uberx'), ('UB', 'UberBlack'), ('US', 'UberSuv'), ('UXL', 'UberXL')], default='UX', max_length=15),
        ),
    ]
