# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20171030_2005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ('nombreMarca',), 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'ordering': ('nombreModelo',), 'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
    ]
