# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20171031_1411'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelo',
            unique_together=set([('marca', 'nombreModelo')]),
        ),
    ]
