# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171101_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ('name',), 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'ordering': ('name',), 'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='nombreMarca',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='nombreModelo',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='modelo',
            unique_together=set([('marca', 'name')]),
        ),
    ]
